CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   email VARCHAR(255),
   CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles (
  role_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL
);

ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users_roles ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE users_roles ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO roles (name) VALUES ('ROLE_USER'),('ROLE_ADMIN');

INSERT INTO users (username, password, email) VALUES
('user', '$2a$12$ASOUUfdL0S5rvqRKQRYVRe/SHekGpDPKnl6YPwdO.oBhkc/E6PB.S', 'user@mail.ru'),
('admin', '$2a$12$ASOUUfdL0S5rvqRKQRYVRe/SHekGpDPKnl6YPwdO.oBhkc/E6PB.S', 'admin@mail.ru');

INSERT INTO users_roles (user_id, role_id) VALUES (1, 2);
